---
- name: Configure macOS
  hosts: mymac
  connection: local
  roles:
    - { role: preflight }
    - { role: hostname }
    - { role: homebrew }
    - { role: appstore }
    - { role: rosetta, when: ansible_machine == "arm64" and rosetta.enabled }
    - { role: git, when: git.enabled }
    - { role: zsh }
    - { role: tmux }
    - { role: ssh, when: ssh.enabled }
    - { role: vim }
    - { role: iterm2 }
    - { role: vscodium }
    - { role: macos_settings }
