---
- name: Ensure ~/.ssh exists
  file:
    path: "{{ ansible_env.HOME }}/.ssh"
    state: directory
    mode: 0700

- name: Ensure ~/.ssh/known_hosts exists
  file:
    path: "{{ ansible_env.HOME }}/.ssh/known_hosts"
    state: touch
    mode: 0644
  changed_when: false

- name: Copy private and public keys
  copy:
    src: "ssh/{{ item.file }}"
    dest: "{{ ansible_env.HOME }}/.ssh/{{ item.file }}"
    owner: "{{ username }}"
    group: "{{ group }}"
    mode: "{{ item.mode }}"
  with_items:
    - { file: id_rsa, mode: "0600" }
    - { file: id_rsa.pub, mode: "0644" }